#Default values for go-web-app-chart.
#This is a YAML-formatted file.
#Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dulshanc/go-web-app
  pullPolicy: IfNotPresent
  #Override the image tag whose default is the chart appVersion.
  tag: "21861803330"

ingress:
  enabled: false
  className: ""
  annotations: {}
  #Used to create an Ingress record.
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific